### ISSUE TITLE
Can't get IPv6 addresses from the host-local plugin

### ISSUE THREAD

**Issue by achanda** [containernetworking/cni#131] opened 2016-02-23 04:15 UTC
The documentation says that it can allocate IPv6 addresses, but here is what I see

```
ubuntu@dev:~/gosrc/src/github.com/appc/cni/bin$ sudo ./host-local < /etc/cni/net.d/10-mynet.conf
{
    "ip4": {
        "ip": "3ffe:ffff:0:1ff::2/64",
        "gateway": "3ffe:ffff:0:1ff::1",
        "routes": [
            {
                "dst": "3ffe:ffff:0:1ff::1/64"
            }
        ]
    },
    "dns": {}
}
ubuntu@dev:~/gosrc/src/github.com/appc/cni/bin$ cat /etc/cni/net.d/10-mynet.conf
{
    "name": "ipv6",
    "ipam": {
        "type": "host-local",
        "subnet": "3ffe:ffff:0:01ff::/64",
        "range-start": "3ffe:ffff:0:01ff::0010",
        "range-end": "3ffe:ffff:0:01ff::0020",
        "routes": [
            { "dst": "3ffe:ffff:0:01ff::1/64" }
        ]
    }
}
ubuntu@dev:~/gosrc/src/github.com/appc/cni/bin$ env | grep CNI
CNI_COMMAND=ADD
CNI_IFNAME=em0
CNI_NETNS=test
CNI_CONTAINERID=f81d4fae-7dec-11d0-a765-00a0c91e6bf6
CNI_PATH=/etc/cni/net.d/10-mynet.conf
```

**Comment by steveeJ** [comment] 2016-02-23 17:23
The official state of IPv6 is not supported, and you found exactly that. The issue tracker for #31 but there hasn't been any ongoing work so far.

**Comment by achanda** [comment] 2016-02-23 19:47
Thanks @steveeJ I noticed that the returned result is correct but the key is wrong. Fixed that in the PR.

**Comment by steveeJ** [comment] 2016-03-02 15:07
Related/If not even duplicate of #111

**Comment by bboreham** [comment] 2017-08-16 15:39
Closed by https://github.com/containernetworking/plugins/pull/12

**Closed by bboreham** 2017-08-16 15:39 UTC
Labels: area/ipv6, component/plugins, kind/enhancement
