### ISSUE TITLE
plugin's should return interface information in the result

### ISSUE THREAD

**Issue by steveeJ** [containernetworking/cni#113] opened 2016-02-01 17:19 UTC
As long as port forwarding is not dealt within CNI there's a lot of work left for the runtime alone.
CNI could make this easier by returning the names/indexes of the created interfaces.

It may be useful to return more/other information than interface names, so an implementation could just add a generic dictionary to the result and let the content depend on the plugins.

**Comment by jonboulle** [comment] 2016-02-01 17:34
I think we talked about this in person a while ago, with some use cases that eluded me now - @thockin any recollection?

**Comment by MikeSpreitzer** [comment] 2016-03-18 14:25
@jonboulle, @thockin: See https://github.com/MikeSpreitzer/kubernetes-contrib/blob/issue/576/cni-plugins/to_docker/README.md#pre-requisites for a reason.

**Comment by steveeJ** [comment] 2016-03-18 15:12
@dcbw do you see #145 as a fix for this one?

**Comment by dcbw** [comment] 2016-03-24 15:40
@steveeJ yeah, I think #145 is a fix for this and I can certainly add host/container interface index to the returned dict.

**Comment by dcbw** [comment] 2016-03-24 15:50
@jonboulle on the last Kube Net SIG we discussed this and @thockin was fuzzy too; he said he'd dump his recollections into #145 or this issue.

I believe one issue was that keeping the interface naming in the runtime keeps each plugin simpler.  libnetwork's approach of the plugin returning an interface prefix and then having libnetwork handle any naming conflicts seems like a nice compromise, but CNI doesn't really have an intermediate layer to do this like libnetwork does.

Also early on there was no way to create an interface in a specific network namespace and thus name conflicts were a fact of life.  These days the kernel (via netlink) supports this just fine:

```
	mv := &netlink.IPVlan{
		LinkAttrs: netlink.LinkAttrs{
			MTU:         conf.MTU,
			Name:        tmpName,
			ParentIndex: m.Attrs().Index,
			Namespace:   netlink.NsFd(int(netns.Fd())),
		},
		Mode: mode,
	}
```

and I think the problem is much less acute, and as long as plugins aren't completely braindead they can easily create the interface within the namespace with their desired name.  We may have conflicts if multiple "networks" are added to the same container, especially with the same plugin that probably uses the same prefix or interface type.  But most of the CNI plugins already create interfaces with a temporary name and then rename to the requested CNI_IFNAME anyway, so they handle it in some measure.

**Comment by dcbw** [comment] 2016-03-24 15:51
To be clear, I don't think requiring the runtime to handle interface naming conflicts is a great strategy.  I feel like that's much more a network plugin operation, and the runtime should simply use the interface name passed back from the plugin.  Also, plugins may actually want to re-use the same interface but just set up different routing or something on it, instead of creating an entirely new one.

**Comment by dcbw** [comment] 2016-03-24 18:21
https://github.com/appc/cni/pull/145 now updated to handle multiple interfaces in the same container.

**Comment by dcbw** [comment] 2019-11-13 16:48
Long since done.

**Closed by dcbw** 2019-11-13 16:48 UTC
Labels: area/usability, component/spec

**Comment by polly400** [comment] 2020-11-15 10:44
byeathread431@gmail.com
