### ISSUE TITLE
skel should not check input when the command is "version" .

### ISSUE THREAD

**Issue by ZhijiaYang** [containernetworking/cni#485] opened 2017-07-20 08:40 UTC
I just read SPEC and cni/skel/skel.go. In the SPEC.md, the "Parameters" of  "report version" command is "None". But `cni/skel/skel.go line:166` check  input for all command.

```
func (t *dispatcher) pluginMain(cmdAdd, cmdDel func(_ *CmdArgs) error, versionInfo version.PluginInfo) *types.Error {
	cmd, cmdArgs, err := t.getCmdArgsFromEnv()
	if err != nil {
		return createTypedError(err.Error())
	}

	switch cmd {
	case "ADD":
		err = t.checkVersionAndCall(cmdArgs, versionInfo, cmdAdd)
	case "DEL":
		err = t.checkVersionAndCall(cmdArgs, versionInfo, cmdDel)
	case "VERSION":
		err = versionInfo.Encode(t.Stdout)
	default:
		return createTypedError("unknown CNI_COMMAND: %v", cmd)
	}

	if err != nil {
		if e, ok := err.(*types.Error); ok {
			// don't wrap Error in Error
			return e
		}
		return createTypedError(err.Error())
	}
	return nil
}

```

I think, there maybe more action of code is not like the SPEC.

**Comment by matthewdupre** [comment] 2017-07-20 13:08
If you look at getCmdArgsFromEnv() more carefully, you'll find that if the command isn't add or del it doesn't require any parameters (except the command itself).

Remember that these arguments are passed as environment variables, so it makes sense to allow non-parameter environment variables to be present.

It's possible I've missed the point here - if you think there's a real problem, could you please post a reproduction with expected and actual behavior?  Otherwise please close this.

**Comment by squeed** [comment] 2017-08-02 15:30
I'm not sure I understand the bug. I can send invalid json and it seems to work:

```
$ echo  '{' | CNI_COMMAND=VERSION CNI_IFNAME=awfeawefawe ./bin/ptp
{"cniVersion":"0.3.1","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1"]}
```

**Comment by rosenhouse** [comment] 2017-11-15 06:21
not able to reproduce this problem, and no response in 3 months.  closing.

**Closed by rosenhouse** 2017-11-15 06:21 UTC
