### ISSUE TITLE
CNI_IFNAME not working in cnitool 0.6.0, is working in 0.5.2

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/cni#630] opened 2019-02-24 14:36 UTC
CNI_PATH="/usr/libexec/cni/" NETCONFPATH="/etc/mesos-cni" CNI_IFNAME="eth1" cnitool-0.5.2 add test-ptp /var/run/netns/testing

creates as expected an interface eth1

**Comment by dcbw** [comment] 2019-02-28 03:52
@mccv1r0 can you take a look at this?

**Comment by mccv1r0** [comment] 2019-02-28 13:37
Isn't this fixed via [PR 587](https://github.com/containernetworking/cni/pull/587)

**Comment by bboreham** [comment] 2019-02-28 14:27
Closing as duplicate of #586.

We should really do a release.

**Closed by bboreham** 2019-02-28 14:27 UTC
Labels: reviewed/duplicate
