### ISSUE TITLE
Binaries not provided since v0.7

### ISSUE THREAD

**Issue by ArchiFleKs** [containernetworking/cni#714] opened 2019-09-25 10:00 UTC
Binaries are not provided anymore since v0.7. It would be nice to continue to provide static build so external deployment tools that depends do not break.

**Comment by bboreham** [comment] 2019-09-25 15:22
Duplicate of #667 
I'll leave this issue open to remind us to mention this in the README and release notes.

**Closed** 2019-11-07 11:41 UTC
