### ISSUE TITLE
flannel plugin should allow setting default routes

### ISSUE THREAD

**Issue by asridharan** [containernetworking/cni#184] opened 2016-04-18 23:39 UTC
Currently the flannel plugin, when generating config for the `delegate` IPAM seems to be setting only routes to the flannel network. However, it should be setting up a default route as well. Otherwise containers launched using the flannel plugin cannot communicate with anything other than containers within the flannel network.

**Comment by ltagliamonte** [comment] 2016-05-02 10:00
+1

**Comment by asridharan** [comment] 2016-05-02 14:09
Submitted a PR: https://github.com/appc/cni/pull/185

**Comment by yifan-gu** [comment] 2016-05-12 23:24
cc @pskrzyns

**Comment by jellonek** [comment] 2016-05-13 07:55
This should be optional. This can not be arbitrary as proposed in PR.
This looks for me like you are trying to solve one simple situation without looking on this from broader perspective.

Try to understand that using network configured with this plugin + other network using bridge/macvlan/other type with correctly set ipam section - you will have conflicting configuration with 2 default routes.

IMO flannel plugin deserves for better method for overriding `ipam` section in `delegate` one, what would provide option to add such things like adding additional routes, including default one.

**Comment by asridharan** [comment] 2016-05-13 14:16
@jellonek I completely agree with you, that we shouldn't be setting only the default route but should allow users to setup a route section which should override the IPAM secion in delegate. Wasn't sure how to do this in `flannel` plugin. Will have to investigate further.

**Comment by jellonek** [comment] 2016-05-16 09:08
I'm not sure, but probably @steveeJ will be the right person to ask, how to do this.

**Comment by pskrzyns** [comment] 2016-05-16 09:20
its quite important cause without it i can't run rktnetes on bare metal

**Comment by asridharan** [comment] 2016-05-16 14:36
This is pretty important for [Mesos](http://mesos.apache.org/) as well.  We just introduced CNI support in Mesos (https://issues.apache.org/jira/secure/Dashboard.jspa). In Mesos, executors (running in containers) need to register back with Agent; without this registration tasks cannot be launched. Flannel seems to be the only plugin which we cannot use out of the box on Mesos due to this limitation. We have been able to use bridge, macvlan and the Calico folks have been able to test their CNI plugins against our implementation as well. Was able to test against a modified version of `Flannel` (where I set the default routes) and that works fine.

**Comment by yifan-gu** [comment] 2016-05-16 17:26
ping @steveeJ @jonboulle @philips

**Comment by steveeJ** [comment] 2016-05-17 12:45
On a deeper look this is a dupliate of #27 and could be solved by a reworked version of #50.
@asridharan can you confirm that this is potentially helpful?

**Comment by jellonek** [comment] 2016-05-17 13:03
As a temporary fix - proposal shown in #50 looks perfectly.

Still, overriding options returned by IPAM (e.x. additional routes) should be possible there.

**Comment by asridharan** [comment] 2016-05-17 13:23
#50 does look promising as a stop gap. Will try it out and report back.

**Comment by steveeJ** [comment] 2016-05-17 13:48
@asridharan it's not finished and the UX around it was never discussed through. I'd appreciate input on that as this is something that will influence default behavior too.

**Comment by jellonek** [comment] 2016-05-17 16:25
Maybe we should add some piece of code checking if there is already set default route and warn user in such situation?
Default route added from multiple plugins (e.x. from default networking + some custom flannel network) still bothers me.

**Comment by tomdee** [comment] 2016-05-18 18:06
Just to confirm my understanding of the way that routes can be specified in the network config. The network config can contain a routes list under the ipam dict. This is passed to the IPAM plugin, which includes a routes list in the ip4 and ip6 sections of the IPAM response. The CNI plugin is then responsible for applying those routes.

Maybe the issue here is with the CNI spec - there's no standard way to wrap or chain plugins. But within the confines of the current spec, the flannel plugin is limited in what config it can place in the IPAM block (as pointed out by @jellonek above). 

I don't see this as a direct dupe of #27. That is about usability, whereas this is a limitation of the flannel plugin that can't be worked around.

I don't have anything against #50, it looks to be limited to the bridge plugin and I think it would fix this current instance of this issue. 

But I don't think it addresses the underlying problem i.e. namely that the flannel plugin doens't allow the user full control of the delagated IPAM plugin (or maybe that the flannel plugin exists at all and that there should be a different mechanism for achieving this wrapping)

**Comment by steveeJ** [comment] 2016-05-20 08:45
@jellonek 
> Maybe we should add some piece of code checking if there is already set default route and warn user in such situation?
> Default route added from multiple plugins (e.x. from default networking + some custom flannel network) still bothers me.

This is something that has to be dealt with in a composition component, see #147 for a discussion about that.

@yifan-gu @dcbw @jell after #50 is merged you need to add the `isDefaultGateway` in the delegation fields in the flannel plugin configuration like so:

```
{
    "name": "myflannel",
    "type": "flannel",
    "delegate": {
        "bridge": "myflannelbr",
        "isDefaultGateway": true
    }
}
```

**Comment by jellonek** [comment] 2016-05-20 08:49
/cc @pskrzyns 
#50 merge is only a first step. We need version bump and then inclusion of this code in `rkt`. It's a bit slow process :/

**Closed** 2016-05-20 23:34 UTC
Labels: component/plugins, kind/feature request
